<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.538">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Maharani Agustin (220204145)">
<meta name="dcterms.date" content="2024-01-17">

<title>Analisis Pengaruh Perdagangan Internasional Terhadap Pertumbuhan Ekonomi Indonesia Periode 2013-2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analisis Pengaruh Perdagangan Internasional Terhadap Pertumbuhan Ekonomi Indonesia Periode 2013-2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Maharani Agustin (220204145) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 17, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<figcaption>Logo Politeknik APP Jakarta</figcaption>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> PENDAHULUAN</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar Belakang</h3>
<p>Pertumbuhan ekonomi menjadi sebuah tolok ukur yang signifikan untuk mengevaluasi kemajuan pembangunan ekonomi di suatu negara. Proses pertumbuhan ekonomi dapat diartikan sebagai perubahan yang berkelanjutan dalam kondisi perekonomian suatu negara menuju kondisi yang lebih baik selama periode tertentu. Salah satu aspek penting dari pertumbuhan ekonomi adalah peningkatan kapasitas produksi dalam perekonomian, yang tercermin dalam peningkatan pendapatan nasional (Rinaldi, 2017:51). Pertumbuhan ekonomi yang positif memiliki potensi untuk meningkatkan kesejahteraan masyarakat.</p>
<p>Beberapa faktor memengaruhi pertumbuhan ekonomi suatu negara, di antaranya adalah kegiatan perdagangan internasional, yang melibatkan ekspor neto dan investasi. Perdagangan internasional merupakan kegiatan pertukaran barang dan jasa antara penduduk suatu negara dengan penduduk negara lain (Doni dkk, 2012:199). Perdagangan ini tidak hanya mencakup ekspor dan impor barang, tetapi juga mencakup ekspor dan impor jasa serta perdagangan modal. Praktik perdagangan internasional, seperti ekspor dan impor minyak bumi, dapat memudahkan negara dalam memenuhi kebutuhannya.</p>
<p>Manfaat dari perdagangan internasional tidak hanya terbatas pada pemenuhan kebutuhan, tetapi juga mencakup kenaikan pendapatan negara, peningkatan investasi, dan lapangan kerja yang lebih luas. Melalui perdagangan internasional, produk-produk domestik dapat dijual tidak hanya di pasar lokal tetapi juga di pasar internasional, yang berpotensi meningkatkan pendapatan nasional suatu negara. Oleh karena itu, perdagangan internasional memiliki dampak yang signifikan terhadap pertumbuhan ekonomi suatu negara. Perdagangan internasional memiliki dampak yang signifikan terhadap pertumbuhan ekonomi suatu negara. Apabila suatu negara lebih aktif dalam kegiatan ekspor dibandingkan impor, maka pendapatan nasional negara tersebut cenderung meningkat, yang pada akhirnya akan berkontribusi positif terhadap pertumbuhan ekonomi. Keuntungan dari perdagangan internasional terletak pada kemampuan suatu negara untuk fokus pada produksi barang dan jasa yang lebih efisien, sehingga dapat diekspor ke pasar internasional. Manfaat dari perdagangan internasional mencakup peningkatan pendapatan negara, cadangan devisa yang bertambah, transaksi modal, dan peluang kerja yang semakin meningkat.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang Lingkup</h3>
<p>Dalam penelitian ini akan diberikan batasan yang akan mencakup tentang perdagangan internasional dan pertumbuhan ekonomi selama 10 tahun terakhir dan ruang lingkup penelitian ini yang hanya menggunakan data dalam kurun waktu 10 tahun (dari tahun 2013 sampai dengan tahun 2022). Kegiatan pengambilan data diperoleh melalui web Kementerian Perdagangan (Kemendag) dan web ITC Trademap.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan Masalah</h3>
<p>Berdasarkan uraian latar belakang masalah diatas, maka terdapat beberapa indikator yang menjadi rumusan masalah dalam penelitian ini. Adapun rumusan masalah tersebut adalah</p>
<ol type="1">
<li>Apakah perdagangan internasional memiliki pengaruh yang signifikan terhadap pertumbuhan ekonomi di Indonesia selama 10 tahun terakhir (2013-2022)?</li>
</ol>
</section>
<section id="tujuan-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-penelitian"><span class="header-section-number">1.4</span> Tujuan Penelitian</h3>
<p>Berdasarkan latar belakang dan permasalahan yang ada maka tujuan dari penelitian ini adalah sebagai berikut :</p>
<ol type="1">
<li>Mengetahui besarnya pengaruh ekspor dan impor terhadap pertumbuhan ekonomi Indonesia</li>
</ol>
</section>
<section id="manfaat-penelitian" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="manfaat-penelitian"><span class="header-section-number">1.5</span> Manfaat Penelitian</h3>
<p>Penelitian ini dapat menyebarkan pengetahuan dan informasi terkini mengenai pengaruh perdagangan internasional terhadap pertumbuhan ekonomi Indonesia. Ini membantu para pembaca untuk memahami dinamika dan faktor-faktor yang terlibat dalam hubungan antara perdagangan internasional dan perkembangan ekonomi suatu negara dan Artikel ini dapat menjadi sumber referensi yang berharga bagi peneliti, akademisi, dan praktisi ekonomi yang tertarik pada topik tersebut.</p>
</section>
<section id="package" class="level3" data-number="1.6">
<h3 data-number="1.6" class="anchored" data-anchor-id="package"><span class="header-section-number">1.6</span> Package</h3>
<p>Packages yang digunakan sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi Pustaka</h2>
<section id="perdagangan-internasional" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="perdagangan-internasional"><span class="header-section-number">2.1</span> Perdagangan Internasional</h3>
<p>Perdagangan internasional berkembang dari pertukaran sederhana dalam bentuk perdagangan tenaga kerja dengan barang dan jasa lainnya. Proses ini kemudian berkembang menjadi perdagangan barang dan jasa pada saat transaksi terjadi, diikuti dengan kompensasi barang dan jasa di masa mendatang (Halwani, 2002:17). Perdagangan internasional semakin meluas hingga mencakup pertukaran antarnegara yang melibatkan aset-aset berisiko seperti saham, valuta asing, dan obligasi, memberikan keuntungan bagi kedua belah pihak, serta semua negara yang terlibat di dalamnya. Hal ini memungkinkan setiap negara untuk melakukan diversifikasi atau penganekaragaman kegiatan perdagangan guna meningkatkan pendapatan mereka.</p>
<p>Perdagangan internasional dianggap sebagai cara untuk meningkatkan kemakmuran suatu bangsa dengan beberapa alasan (Sobri, 2011:2):</p>
<ol type="1">
<li>Tidak semua negara memiliki peralatan produksi atau kondisi ekonomi yang sama, baik dari segi kualitas maupun kuantitas.</li>
<li>Adanya perbedaan biaya produksi suatu barang antar negara karena ketidaksetaraan kondisi-kondisi tersebut. Suatu negara mungkin lebih menguntungkan untuk mengimpor suatu barang daripada memproduksinya sendiri. Dengan adanya perdagangan, negara dapat memperoleh sejumlah barang dengan harga yang lebih murah dibandingkan dengan memproduksi sendiri di dalam negeri.</li>
<li>Perdagangan memungkinkan negara untuk menghindari jenis produksi suatu barang yang memiliki biaya produksi tinggi karena keterbatasan faktor produksi yang diperlukan, dan kemudian melakukan pertukaran. Dengan adanya perdagangan, negara-negara yang terlibat dapat saling memperoleh sejumlah barang dengan total biaya lebih rendah.</li>
</ol>
<p>Dengan demikian, perdagangan internasional dianggap sebagai mekanisme yang dapat memberikan manfaat ekonomi melalui pemanfaatan kelebihan komparatif antar negara, memungkinkan penghematan biaya produksi, dan meningkatkan kesejahteraan suatu bangsa.Boediono (2001:161) mendefinisikan inflasi sebagai suatu kecenderungan kenaikan harga secara umum dan terus-menerus. Untuk dianggap sebagai inflasi, kenaikan harga tidak hanya terjadi pada satu atau dua barang, melainkan meluas dan berdampak pada sebagian besar barang lainnya. Fluktuasi inflasi dapat mempengaruhi kegiatan perekonomian, dengan dampak utama berupa penurunan daya beli masyarakat karena nilai riil mata uang mengalami penurunan.</p>
</section>
<section id="pertumbuhan-ekonomi" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="pertumbuhan-ekonomi"><span class="header-section-number">2.2</span> Pertumbuhan Ekonomi</h3>
<p>Pertumbuhan ekonomi adalah suatu proses perubahan yang berkelanjutan dalam kondisi perekonomian suatu negara, menuju keadaan yang lebih baik selama periode tertentu. Dalam konteks ini, pertumbuhan ekonomi dapat diartikan sebagai peningkatan kapasitas produksi dalam perekonomian, yang tercermin dalam bentuk peningkatan pendapatan nasional (Rinaldi, 2017:51). Definisi pertumbuhan ekonomi menurut Munandar (2016:23) mencerminkan sejauh mana aktivitas perekonomian akan menghasilkan penambahan pendapatan masyarakat dalam suatu periode tertentu. Nasrullah (2014) menekankan bahwa suatu negara dapat dianggap memiliki kondisi perekonomian yang baik dengan menghitung tingkat pertumbuhan ekonomi yang tinggi atau, secara sederhana, dengan mengukur peningkatan jumlah produksi barang dan jasa dalam perekonomian, yang dikenal dengan istilah Produk Domestik Bruto (PDB).</p>
</section>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode Penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<colgroup>
<col style="width: 9%">
<col style="width: 33%">
<col style="width: 32%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Tahun</th>
<th>Nilai Ekspor (ribu USD)</th>
<th>Nilai Impor (ribu USD)</th>
<th>PDB (Juta Rupiah)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2013</td>
<td>182.551.754</td>
<td>186.628.631</td>
<td>8.156.497.800</td>
</tr>
<tr class="even">
<td>2014</td>
<td>176.036.194</td>
<td>178.179.340</td>
<td>8.564.866.600</td>
</tr>
<tr class="odd">
<td>2015</td>
<td>150.282.258</td>
<td>142.694.804</td>
<td>8.982.517.100</td>
</tr>
<tr class="even">
<td>2016</td>
<td>144.494.206</td>
<td>135.652.914</td>
<td>9.434.613.400</td>
</tr>
<tr class="odd">
<td>2017</td>
<td>168.810.637</td>
<td>156.925.150</td>
<td>9.912.928.100</td>
</tr>
<tr class="even">
<td>2018</td>
<td>180.215.036</td>
<td>188.711.246</td>
<td>10.425.851.900</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>167.682.996</td>
<td>171.275.737</td>
<td>10.425.851.900</td>
</tr>
<tr class="even">
<td>2020</td>
<td>163.306.490</td>
<td>141.622.127</td>
<td>10.949.155.400</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>231.587.887</td>
<td>195.694.490</td>
<td>10.722.999.300</td>
</tr>
<tr class="even">
<td>2022</td>
<td>291.979.103</td>
<td>237.447.057</td>
<td>11.120.077.900</td>
</tr>
</tbody>
</table>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang digunakan dalam penelitian ini adalah metode regresi linier berganda. Metode regresi linier berganda untuk menghitung besarnya pengaruh ekspor dan impor terhadap pertumbuhan ekonomi Indonesia. Metode analisis yang digunakan dalam penelitian ini adalah metode kuantitatif dan penjabaran deskriptif. Teknik analisis kuantitatif merupakan analisis yang dilakukan dengan perhitungan angka-angka dan Metode deskriptif digunakan untuk membuat gambaran secara sistematis dan faktual mengenai gambaran perkembangan dari setiap variabel.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Pada bagian ini dapat ditampilkan data yang telah dikumpulkan :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'C:/Dokumen/Metodologi Penelitian/Maharani agustin'</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">read_excel</span>(<span class="st">"Data Metodologi Penelitian.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
           X         Y         S
       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 182551754 186628631  8156498.
 2 176036194 178179340  8564867.
 3 150282258 142694804  8982517.
 4 144494206 135652914  9434613.
 5 168810637 156925150  9912928.
 6 180215036 188711246 10425852.
 7 167682996 171275737 10949155.
 8 163306490 141622127 10722999.
 9 231587887 195694490 11120078.
10 291979103 237447057 11710398.</code></pre>
</div>
</div>
<p>Diketahui :</p>
<p>X = Nilai Ekspor</p>
<p>Y = Nilai Impor</p>
<p>S = PDB Indonesia</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"Data Metodologi Penelitian.xlsx"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>X<span class="sc">+</span>Y, <span class="at">y=</span>S))<span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">'blue'</span>, <span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Plot Terhadap PDB Indonesia"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Nilai Ekspor &amp; Impor"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"PDB Indonesia"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Sumber:  Trade Map dan Kemendag"</span>) <span class="sc">+</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil pengaruh perdagangan internasional terhadap pertumbuhan ekonomi indonesia diestimasi menggunakan regresi univariat. Hasilnya ditunjukkan sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"Data Metodologi Penelitian.xlsx"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(S<span class="sc">~</span>X<span class="sc">+</span>Y,<span class="at">data=</span>dat)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = S ~ X + Y, data = dat)

Residuals:
     Min       1Q   Median       3Q      Max 
-1353903  -574745   -39026   477557  1506768 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)  8.621e+06  2.045e+06   4.216  0.00396 **
X            3.439e-02  1.891e-02   1.819  0.11177   
Y           -2.887e-02  2.691e-02  -1.073  0.31895   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1004000 on 7 degrees of freedom
Multiple R-squared:  0.4405,    Adjusted R-squared:  0.2806 
F-statistic: 2.755 on 2 and 7 DF,  p-value: 0.131</code></pre>
</div>
</div>
<p>Dilakukan uji simultan (Uji F) untuk mengevaluasi seberapa besar dampak dari variabel independen, yakni perdagangan internasional, terhadap variabel dependen, yaitu pertumbuhan ekonomi Indonesia. Berdasarkan hasil regresi, diperoleh nilai F-statistic sebesar 2.755 dengan probabilitas 0.131. Dengan demikian, dapat disimpulkan bahwa perdagangan internasional memiliki pengaruh terhadap pertumbuhan ekonomi Indonesia selama periode 2013-2022.</p>
<p>Penggunaan nilai R² bertujuan untuk menunjukkan sejauh mana variabel independen memengaruhi variabel dependen. Menurut tabel di atas, nilai R² menunjukkan bahwa perdagangan internasional mempengaruhi pertumbuhan ekonomi Indonesia sebesar 0.4405 atau 44,05%. Artinya, sebanyak 44,05% dari perkembangan ekonomi Indonesia dapat diatribusikan kepada perdagangan internasional. Sementara itu, sebanyak 55,95% dipengaruhi oleh faktor-faktor lain yang tidak tercakup dalam penelitian ini.</p>
<p>Selanjutnya, pada analisis variabel X (ekspor), ditemukan t-value sebesar 1.819 dengan probabilitas 0.11177 &gt; α=0,1. Dari hasil ini, dapat disimpulkan bahwa secara parsial, nilai ekspor memiliki pengaruh yang signifikan terhadap pertumbuhan ekonomi Indonesia selama periode 2013-2022. Di sisi lain, pada variabel Y (impor), ditemukan t-value -1.073 dengan probabilitas 0.31895 &gt; α=0,1. Oleh karena itu, secara parsial, dapat diindikasikan bahwa nilai impor tidak memiliki pengaruh yang signifikan terhadap pertumbuhan ekonomi Indonesia pada periode tersebut.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Berdasarkan penelitian ini dapat disimpulkan bahwa perdagangan internasional memiliki dampak signifikan terhadap pertumbuhan ekonomi Indonesia, terutama pada sektor ekspor. Perdagangan internasional, sebagai variabel independen, memainkan peran kunci dalam mempengaruhi fluktuasi pertumbuhan ekonomi Indonesia. Penelitian ini menggambarkan bahwa proses dalam perdagangan internasional dapat menjadi pendorong utama naik atau turunnya pertumbuhan ekonomi. Dengan demikian, pemahaman mendalam tentang hubungan ini dapat menjadi landasan untuk merancang kebijakan ekonomi yang tepat guna, terutama dalam mengoptimalkan kegiatan ekspor sebagai salah satu elemen penting dalam mendorong pertumbuhan ekonomi Indonesia.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>ITC Trade Map. (2022). Retrieved January 17, 2024, from https://www.trademap.org/</p>
<p>Kementrian Perdagangan. (2012-2021). Profil komoditas. Kementrian Perdagangan, 33. https://satudata.kemendag.go.id/data-informasi/perdagangan-dalam-negeri/produk-domestik-bruto</p>
<p>Zatira, D., Sari, T. N., &amp; Apriani, M. D. (2021). Perdagangan internasional terhadap pertumbuhan ekonomi Indonesia. Jurnal Ekonomi-QU, 11(1), 88-96.</p>
<p>Wulandari, L. M., &amp; Zuhri, S. (2019). Pengaruh perdagangan internasional terhadap pertumbuhan ekonomi Indonesia Tahun 2007-2017. Jurnal REP (Riset Ekonomi Pembangunan), 4(2), 119-127.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>